apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager-acme
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    # Replace the EMAIL-ADDRESS placeholder with the correct email
    # The ACME server URL (use the staging server, which is usually used for testing purposes)
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: mwoodpatrick@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    # HTTP01 and DNS01 are two different [challenges](https://letsencrypt.org/docs/challenge-types/)
    # that Cert Manager uses to verify that you are the owner of your domain.
    solvers:
      - http01:
          ingress:
            # class: nginx?
            ingressClassName: nginx
