apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: cert-manager-acme
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
    # cert-manager.io/issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - whoami.example.com
    secretName: whoami-ingress-tls
  rules:
  - host: whoami.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              number: 80
