apiVersion: v1
kind: Namespace
metadata:
  name: archlinux
  labels:
    name: archlinux
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: archlinux
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: arch
  name: arch
  namespace: archlinux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arch
  strategy: {}
  template:
    metadata:
      labels:
        app: arch
    spec:
      containers:
        - name: arch
          image: archlinux
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /data
            - name: project-directory
              mountPath: /projects
          ports:
            - containerPort: 80
          command: ["/bin/sleep", "3650d"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: project-directory
          hostPath:
            path: /projects
            type: Directory
