apiVersion: v1
kind: Namespace
metadata:
  name: debian
  labels:
    name: debian
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: debian
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debian
  name: debian
  namespace: debian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian
  strategy: {}
  template:
    metadata:
      labels:
        app: debian
    spec:
      containers:
        - name: debian
          image: mcr.microsoft.com/devcontainers/php:0-8.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /data
            - name: project-directory
              mountPath: /projects
          ports:
            - containerPort: 80
          command: ["/bin/sleep", "3650d"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: project-directory
          hostPath:
            path: /projects
            type: Directory
