apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
  name: wordpress
  namespace: wordpress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - wp.westie.dev.to
    secretName: wordpress-ingress-tls
  rules:
    - host: wp.westie.dev.to
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: wordpress
              port: 
                number: 80
